name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Encode and Replace API_KEY
        run: |
          ENCODED_KEY=$(echo -n "${{ secrets.GEMINI_API_KEY }}" | base64)
          sed -i "s/API_KEY_HERE/$ENCODED_KEY/g" ./src/app.js

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install -g javascript-obfuscator

      - name: Obfuscate JavaScript
        run: |
          mkdir -p dist
          javascript-obfuscator src/ --output dist/
      
      - name: Copy contents
        run: |
          cp src/index.html dist/
          mkdir -p dist/img/
          cp src/img/* dist/img/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
